"""create_table

Revision ID: 27304ef017c6
Revises: 6487e34bb0b5
Create Date: 2026-01-28 13:33:41.286242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27304ef017c6'
down_revision = '6487e34bb0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
