"""add app config

Revision ID: 441d62ada467
Revises: 3b3c1bc13340
Create Date: 2026-07-08 11:01:42.086701

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "441d62ada467"
down_revision = "3b3c1bc13340"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column(
            "model_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "dialog_round", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "preset_prompt",
            sa.Text(),
            server_default=sa.text("''::text"),
            nullable=False,
        ),
        sa.Column(
            "tools",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "agents",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "workflows",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "retrieval_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "long_term_memory",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "opening_statement",
            sa.Text(),
            server_default=sa.text("''::text"),
            nullable=False,
        ),
        sa.Column(
            "opening_questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "speech_to_text",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "text_to_speech",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "multimodal",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "mcp_server",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "suggested_after_answer",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{\"enable\": true}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "review_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_app_config_id"),
    )
    op.create_table(
        "app_config_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column(
            "model_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "dialog_round", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "preset_prompt",
            sa.Text(),
            server_default=sa.text("''::text"),
            nullable=False,
        ),
        sa.Column(
            "tools",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "agents",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "workflows",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "datasets",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "retrieval_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "long_term_memory",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "opening_statement",
            sa.Text(),
            server_default=sa.text("''::text"),
            nullable=False,
        ),
        sa.Column(
            "opening_questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "speech_to_text",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "multimodal",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "text_to_speech",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "mcp_server",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "suggested_after_answer",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{\"enable\": true}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "review_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "config_type",
            sa.String(length=255),
            server_default=sa.text("''::character varying"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_app_config_version_id"),
    )
    with op.batch_alter_table("app_config_version", schema=None) as batch_op:
        batch_op.create_index("app_config_version_app_id_idx", ["app_id"], unique=False)

    with op.batch_alter_table("app", schema=None) as batch_op:
        batch_op.add_column(sa.Column("app_config_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("draft_app_config_id", sa.UUID(), nullable=True))
        batch_op.add_column(
            sa.Column("debug_conversation_id", sa.UUID(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "en_name",
                sa.String(length=255),
                server_default=sa.text("''::character varying"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "token",
                sa.String(length=255),
                server_default=sa.text("''::character varying"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("mode", sa.Integer(), server_default=sa.text("0"), nullable=False)
        )
        batch_op.alter_column("account_id", existing_type=sa.UUID(), nullable=False)
        batch_op.drop_index(batch_op.f("idx_app_account_id"))
        batch_op.create_index("app_account_id_idx", ["account_id"], unique=False)
        batch_op.create_index("app_token_idx", ["token"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app", schema=None) as batch_op:
        batch_op.drop_index("app_token_idx")
        batch_op.drop_index("app_account_id_idx")
        batch_op.create_index(
            batch_op.f("idx_app_account_id"), ["account_id"], unique=False
        )
        batch_op.alter_column("account_id", existing_type=sa.UUID(), nullable=True)
        batch_op.drop_column("mode")
        batch_op.drop_column("token")
        batch_op.drop_column("en_name")
        batch_op.drop_column("debug_conversation_id")
        batch_op.drop_column("draft_app_config_id")
        batch_op.drop_column("app_config_id")

    with op.batch_alter_table("app_config_version", schema=None) as batch_op:
        batch_op.drop_index("app_config_version_app_id_idx")

    op.drop_table("app_config_version")
    op.drop_table("app_config")
    # ### end Alembic commands ###
