"""add query and uniqueness indexes

Revision ID: df55fdc0bb80
Revises: 808dd647abb4
Create Date: 2026-09-17 14:26:17.157839

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df55fdc0bb80"
down_revision = "808dd647abb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index("account_email_idx", ["email"], unique=True)

    with op.batch_alter_table("account_oauth", schema=None) as batch_op:
        batch_op.create_index(
            "account_oauth_account_id_idx", ["account_id"], unique=False
        )
        batch_op.create_index(
            "account_oauth_openid_provider_idx", ["openid", "provider"], unique=True
        )

    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("api_key_api_key_idx"))
        batch_op.create_index("api_key_api_key_idx", ["api_key"], unique=True)

    with op.batch_alter_table("api_tool", schema=None) as batch_op:
        batch_op.create_index("api_tool_account_id_idx", ["account_id"], unique=False)
        batch_op.create_index(
            "api_tool_provider_id_name_idx", ["provider_id", "name"], unique=True
        )

    with op.batch_alter_table("api_tool_provider", schema=None) as batch_op:
        batch_op.create_index(
            "api_tool_provider_account_id_name_idx", ["account_id", "name"], unique=True
        )

    with op.batch_alter_table("app", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("app_token_idx"))
        batch_op.create_index(
            "app_token_idx",
            ["token"],
            unique=True,
            postgresql_where=sa.text("token IS NOT NULL AND token <> ''"),
        )

    with op.batch_alter_table("app_config", schema=None) as batch_op:
        batch_op.create_index("app_config_app_id_idx", ["app_id"], unique=False)

    with op.batch_alter_table("app_config_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("app_config_version_app_id_idx"))
        batch_op.create_index(
            "app_config_version_app_id_config_type_version_idx",
            ["app_id", "config_type", "version"],
            unique=True,
        )

    with op.batch_alter_table("app_dataset_join", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("app_dataset_join_app_id_dataset_id_idx"))
        batch_op.create_index(
            "app_dataset_join_app_id_dataset_id_idx",
            ["app_id", "dataset_id"],
            unique=True,
        )
        batch_op.create_index(
            "app_dataset_join_dataset_id_idx", ["dataset_id"], unique=False
        )

    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.create_index(
            "conversation_app_user_source_pinned_created_idx",
            ["app_id", "created_by", "invoke_from", "is_pinned", "created_at"],
            unique=False,
            postgresql_where=sa.text("is_deleted = false"),
        )

    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("dataset_account_id_name_idx"))
        batch_op.create_index(
            "dataset_account_id_name_idx", ["account_id", "name"], unique=True
        )

    with op.batch_alter_table("dataset_query", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("dataset_query_dataset_id_idx"))
        batch_op.create_index(
            "dataset_query_dataset_id_created_at_idx",
            ["dataset_id", "created_at"],
            unique=False,
        )

    with op.batch_alter_table("keyword_table", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("keyword_table_dataset_id_idx"))
        batch_op.create_index(
            "keyword_table_dataset_id_idx", ["dataset_id"], unique=True
        )

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(
            "message_app_created_at_idx", ["app_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "message_conversation_created_at_idx",
            ["conversation_id", "created_at"],
            unique=False,
        )

    with op.batch_alter_table("message_agent_thought", schema=None) as batch_op:
        batch_op.create_index(
            "message_agent_thought_message_id_position_idx",
            ["message_id", "position"],
            unique=False,
        )

    with op.batch_alter_table("segment", schema=None) as batch_op:
        batch_op.create_index("segment_node_id_idx", ["node_id"], unique=True)

    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("workflow_account_id_idx"))
        batch_op.drop_index(batch_op.f("workflow_tool_call_name_idx"))
        batch_op.create_index(
            "workflow_account_id_tool_call_name_idx",
            ["account_id", "tool_call_name"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.drop_index("workflow_account_id_tool_call_name_idx")
        batch_op.create_index(
            batch_op.f("workflow_tool_call_name_idx"), ["tool_call_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("workflow_account_id_idx"), ["account_id"], unique=False
        )

    with op.batch_alter_table("segment", schema=None) as batch_op:
        batch_op.drop_index("segment_node_id_idx")

    with op.batch_alter_table("message_agent_thought", schema=None) as batch_op:
        batch_op.drop_index("message_agent_thought_message_id_position_idx")

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index("message_conversation_created_at_idx")
        batch_op.drop_index("message_app_created_at_idx")

    with op.batch_alter_table("keyword_table", schema=None) as batch_op:
        batch_op.drop_index("keyword_table_dataset_id_idx")
        batch_op.create_index(
            batch_op.f("keyword_table_dataset_id_idx"), ["dataset_id"], unique=False
        )

    with op.batch_alter_table("dataset_query", schema=None) as batch_op:
        batch_op.drop_index("dataset_query_dataset_id_created_at_idx")
        batch_op.create_index(
            batch_op.f("dataset_query_dataset_id_idx"), ["dataset_id"], unique=False
        )

    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_index("dataset_account_id_name_idx")
        batch_op.create_index(
            batch_op.f("dataset_account_id_name_idx"),
            ["account_id", "name"],
            unique=False,
        )

    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.drop_index(
            "conversation_app_user_source_pinned_created_idx",
            postgresql_where=sa.text("is_deleted = false"),
        )

    with op.batch_alter_table("app_dataset_join", schema=None) as batch_op:
        batch_op.drop_index("app_dataset_join_dataset_id_idx")
        batch_op.drop_index("app_dataset_join_app_id_dataset_id_idx")
        batch_op.create_index(
            batch_op.f("app_dataset_join_app_id_dataset_id_idx"),
            ["app_id", "dataset_id"],
            unique=False,
        )

    with op.batch_alter_table("app_config_version", schema=None) as batch_op:
        batch_op.drop_index("app_config_version_app_id_config_type_version_idx")
        batch_op.create_index(
            batch_op.f("app_config_version_app_id_idx"), ["app_id"], unique=False
        )

    with op.batch_alter_table("app_config", schema=None) as batch_op:
        batch_op.drop_index("app_config_app_id_idx")

    with op.batch_alter_table("app", schema=None) as batch_op:
        batch_op.drop_index(
            "app_token_idx",
            postgresql_where=sa.text("token IS NOT NULL AND token <> ''"),
        )
        batch_op.create_index(batch_op.f("app_token_idx"), ["token"], unique=False)

    with op.batch_alter_table("api_tool_provider", schema=None) as batch_op:
        batch_op.drop_index("api_tool_provider_account_id_name_idx")

    with op.batch_alter_table("api_tool", schema=None) as batch_op:
        batch_op.drop_index("api_tool_provider_id_name_idx")
        batch_op.drop_index("api_tool_account_id_idx")

    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index("api_key_api_key_idx")
        batch_op.create_index(
            batch_op.f("api_key_api_key_idx"), ["api_key"], unique=False
        )

    with op.batch_alter_table("account_oauth", schema=None) as batch_op:
        batch_op.drop_index("account_oauth_openid_provider_idx")
        batch_op.drop_index("account_oauth_account_id_idx")

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index("account_email_idx")

    # ### end Alembic commands ###
